path: C:\Users\Admin\OneDrive\Documents\Shit\year2\Semester2\Computer Vision\CV Final
  Project\cv-shelf-project\data\processed\groceries6
train: train/images
val: valid/images
test: test/images
names:
- water
- milk
- juice
- cereal
- chips
- pasta
