path: C:\Users\admin\Documents\MI_PROJECTS\CV_shelf\cv-shelf-project\data\processed\groceries6
train: train/images
val: valid/images
test: test/images

nc: 6
names:
  - water
  - milk
  - juice
  - cereal
  - chips
  - pasta